user = "username"
password = "passwd"
dbs = [
    "final:final@final.test.com",
    "shard0:shard_0@shardxx.test.com",
    "shard1:shard_1@shardxx.test.com",
    "shard2:shard_2@shardxx.test.com",
    "shard3:shard_3@shardxx.test.com",
    "shard4:shard_4@shardxx.test.com",
    "shard5:shard_5@shardxx.test.com",
    "shard6:shard_6@shardxx.test.com",
    "shard7:shard_7@shardxx.test.com",
    "shard8:shard_8@shardxx.test.com",
    "shard9:shard_9@shardxx.test.com",
    "shard10:shard_10@shardxx.test.com",
    "shard11:shard_11@shardxx.test.com",
    "shard12:shard_12@shardxx.test.com",
    "shard13:shard_13@shardxx.test.com",
    "shard14:shard_14@shardxx.test.com",
    "shard15:shard_15@shardxx.test.com",
    "shard16:shard_16@shardxx.test.com",
    "shard17:shard_17@shardxx.test.com",
    "shard18:shard_18@shardxx.test.com",
    "shard19:shard_19@shardxx.test.com",
    "shard20:shard_20@shardxx.test.com",
    "shard21:shard_21@shardxx.test.com",
    "shard22:shard_22@shardxx.test.com",
    "shard23:shard_23@shardxx.test.com",
    "shard24:shard_24@shardxx.test.com",
    "shard25:shard_25@shardxx.test.com",
    "shard26:shard_26@shardxx.test.com",
    "shard27:shard_27@shardxx.test.com",
    "shard28:shard_28@shardxx.test.com",
    "shard29:shard_29@shardxx.test.com",
    "shard30:shard_30@shardxx.test.com",
    "shard31:shard_31@shardxx.test.com"
    ]